### ISSUE TITLE
Dismiss PR approval when changing from "Approved -> Needs Careful Review"

### ISSUE THREAD

**Issue by ChrisCarini** [sturdy-dev/codeball-action#92]
## Details

I have a PR (see link in 'info' section below) that followed the below order of events:

1. Codeball ran on a PR
2. Codeball result was confidence `0.98` ([workflow run link](https://github.com/ChrisCarini/sample-intellij-plugin/runs/8283583110?check_suite_focus=true))
    1. PR approved by Codeball
    2. PR labeled `codeball:approved` by Codeball
3. A merge commit was pushed to the branch
4. Codeball ran a second time on the PR
5. Codeball result was confidence `0.137` ([workflow run link](https://github.com/ChrisCarini/sample-intellij-plugin/runs/8283626812?check_suite_focus=true))
    1. PR labeled `codeball:needs-careful-review` by Codeball

### Screenshot
<img width="622" alt="Screen Shot 2022-09-10 at 02 31 46" src="https://user-images.githubusercontent.com/6374067/189477596-659323ef-0048-4914-8d99-6f78e0448554.png">

## Expected
In step `5.ii`, the previous approval on the PR approval is removed/dismissed.

## Actual
The PR remained with an approval.

## Info

**PR:** https://github.com/ChrisCarini/sample-intellij-plugin/pull/87
**Codeball Workflow:** https://github.com/ChrisCarini/sample-intellij-plugin/blob/master/.github/workflows/codeball.yml

**Comment by zegl** [comment]
Hey, thanks for opening an issue! 👏 

This makes a lot of sense. I've had a habit of enabling the **"Dismiss stale pull request approvals when new commits are pushed"** branch protection rule on GitHub (see screenshot) that does this automatically, which is why it a bit of a oversight that Codeball does not do this by itself yet.

Adding it to Codeball should be easy, I'll let you know when it's ready!

<img width="792" alt="Screenshot 2022-09-12 at 09 59 39" src="https://user-images.githubusercontent.com/47952/189602459-50b311fb-680c-4547-b08d-b0b2231ae9fe.png">

**Comment by ChrisCarini** [comment]
Thank you @zegl - what's weird is I *do* have that setting enabled on my repos, so I'm not sure exactly why it did *not* revoke the approval. Either way, I really appreciate you knocking this one out!
